./long_long_problem2 long_long_A long_long_B long_long_C 0
./long_long_problem2 long_long_A long_long_B long_long_C 1
./long_long_problem2 long_long_A long_long_B long_long_C 2
./long_long_problem2 long_long_A long_long_B long_long_C 3
./long_long_problem2 long_long_A long_long_B long_long_C 4
./long_long_problem2 long_long_A long_long_B long_long_C 5
./int_exec int_A int_B int_C 0
./int_exec int_A int_B int_C 1
./int_exec int_A int_B int_C 2
./int_exec int_A int_B int_C 3
./int_exec int_A int_B int_C 4
./int_exec int_A int_B int_C 5
